config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check # returns 500 if the app boots with exceptions, otherwise 200

  root to: "products#index"

  get "cart", to: "orders#edit"
  resource :order, only: :create do
    scope module: :orders do
      resources :items, only: [:create, :update, :destroy]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :order
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :items, dependent: :destroy do
    def add_from_product(product)
      if (item = find_by(product:))
        item.increment(:quantity)
      else
        item = new(product:)
      end

      item.save!
    end
  end

  enum status: {submitted: 0, fulfilled: 1}

  validates :items, on: :submit, presence: {message: "must have at least one item"}

  validates :total_price, numericality: {less_than_or_equal_to: 99_999_999.99}

  broadcasts_refreshes

  def total_item_count
    items.sum(:quantity)
  end

  def total_price
    items.sum(&:total_price)
  end

  def submit
    self.status = :submitted

    save!(context: :submit)
  end
end

app/models/order/item.rb
class Order::Item < ApplicationRecord
  belongs_to :order, default: -> { Current.order }, touch: true

  belongs_to :product, required: false

  validates :price, :quantity, :name, presence: true
  validates :price, :quantity, numericality: {greater_than: 0}

  before_validation :set_attributes_from_product, on: :create, if: -> { product.present? }

  def total_price
    price * quantity
  end

  private

  def set_attributes_from_product
    self.name ||= product.name
    self.price ||= product.price
  end
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, :price, presence: true
  validates :price, numericality: {greater_than: 0}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_order

  private

  def set_current_order
    if (order = Order.where(status: nil).find_by(id: cookies.signed[:order_id]))
      Current.order = order
    else
      Current.order = Order.create!
      cookies.permanent.signed[:order_id] = Current.order.id
    end
  end
end

app/controllers/orders/items_controller.rb
class Orders::ItemsController < ApplicationController
  before_action :set_item, except: :create

  def create
    product = Product.find(params[:product_id])
    Current.order.items.add_from_product(product)

    redirect_back_or_to root_path
  end

  def update
    if @item.update(item_params)
      redirect_to cart_path
    else
      render "orders/edit", status: :unprocessable_entity
    end
  end

  def destroy
    @item.destroy!

    redirect_back_or_to cart_path
  end

  private

  def set_item
    @item = Current.order.items.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:quantity)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def edit
    @order = Current.order
  end

  def create
    @order = Current.order.submit
    redirect_to root_path, notice: "Order submitted!"
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def monetarily_format(amount)
    "$#{number_with_precision(amount, precision: 2)}"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoShop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "https://cdn.simplecss.org/simple.min.css" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <% turbo_refreshes_with method: :morph, scroll: :preserve %>

    <%= yield :head %> <%# used by Turbo Drive helpers %>
  </head>

  <body>
    <%= turbo_stream_from Current.order %>

    <% if flash.notice %>
      <p class="notice">
        <%= flash.notice %>
      </p>
    <% end %>

    <header>
      <nav>
        <ul>
          <li><%= link_to "Products", root_path %></li>
          <li><%= link_to "Cart (#{Current.order.total_item_count})", cart_path %></li>
        </ul>
      </nav>
    </header>

    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/orders/edit.html.erb
<table>
  <% Current.order.items.each do |item| %>
    <tr id="<%= dom_id(item) %>">
      <td><%= item.name %></td>
      <td><%= monetarily_format item.price %></td>

      <td>
        <%= link_to "➖", order_item_path(item, "item[quantity]": item.quantity - 1),
                    "data-turbo-method": "patch" %>

        x <%= item.quantity %>

        <%= link_to "➕", order_item_path(item, "item[quantity]": item.quantity + 1),
                    "data-turbo-method": "patch" %>
      </td>

      <td>
        <%= link_to "🗑️", order_item_path(item), "data-turbo-method": "delete" %>
      </td>
    </tr>
  <% end %>

  <tr>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>

  <tr>
    <td>Subtotal</td>
    <td><%= monetarily_format Current.order.total_price %></td>
    <td></td>
    <td></td>
  </tr>
</table>

app/views/products/index.html.erb
<h1>Products</h1>

<% @products.each do |product| %>
  <article id="<%= dom_id(product) %>">
    <h2><%= product.name %></h2>
    <h3><%= monetarily_format product.price %></h3>

    <%= button_to "Add to cart", order_items_path, params: {product_id: product.id} %>
  </article>
<% end %>